### PR TITLE
Adding removeRule method to lexer class

### PR DESCRIPTION
**Pull request by KalenAnson**
We needed support for dynamically changing the active rule set depending on the lexing context within our application.

### CODE REVIEW

**Comment by aaditmshah** [comment]
I don't think this is necessary since `Lexer` already provides [start conditions](http://dinosaur.compilertools.net/flex/flex_11.html). By default an instance of `Lexer` (let's call it `myLexer`) is in the state `0` (i.e. `myLexer.state = 0`). You can change the state any time you want by assigning a different unsigned integer to it.

Now, the `addRule` method takes an optional third argument (i.e. an array of start conditions). By default, this array is `[0]`. Hence, by default every rule is active because we're initially in the state `0`. However, we could give `addRule` any array of start conditions (e.g. `[2, 4]`). In this example, the given rule would only be active in states `2` and `4`, thereby creating a "mini-lexer".

There's also a distinction between exclusive states (i.e. even numbered states, as in the previous example) and inclusive states (i.e. odd numbered states). Exclusive states only activate those rules which have the given state in their array of start conditions (e.g. in state `2`, only those rules which have `2` in their array of start conditions will be activated). On the other hand, inclusive states also activate those rules whose array of start conditions is exactly `[0]` (e.g. in state `1`, both, those rules which have `1` in their array of start conditions as well as those rules whose array of start conditions is exactly `[0]` will be activated).

Finally, there's one exception. Rules whose array of start conditions is empty are always active, regardless of which state the lexer is in. This can be especially useful for debugging. Hope that helps.

**Comment by KalenAnson** [comment]
Ah, a very helpful explanation of the `start conditions` feature. I agree, this PR is unnecessary given the features you just clarified. I appreciate the clarification and your work on the great module.

**Comment by KalenAnson** [comment]
On further discovery, the start conditions are quite suitable for situations where I am using the lexer in a stand alone situation. However when I use `lex` as a custom lexer for, say the `jison` parser, I lose scope on the `myLexer.state` variable.

Consider a simplified example:

    /*\
    |*| Create the parser (an instance of jison) and used a defined grammar (above, omitted)
    \*/
    self.parser = new Parser(grammar);
    /*\
    |*| Save an instance of the lexer
    \*/
    self.lexer = new Lexer();
    /*\
    |*| Make the parser use the lexer
    \*/
    self.parser.lexer = self.lexer;
    ...
    // Add rules to the lexer that require stateful lexing using the internal `this.state`
    ...
    /*\
    |*| Begin parsing.
    \*/
    value = self.parser.parse(str);

The final line where I invoke the parser (`jison`), the parsing module calls `lex`'s public `setInput()` method, so far so good. However on line 53 of `lexer.js` the `setInput()` method resets the internal state of the lexer to `0`.

In a stand alone lexing context, after calling `setInput()` I can change the `state` variable to suit my lexing needs. However when the lexer is used with another library that uses a simplified API (calls to `setInput()` internally) I no longer can adjust the lexing context.

## Question
Do you see a valid use case for changing the `setInput` method to respect a predefined `state`, possibly set using a setter method, or am I going at this all wrong?

**Comment by aaditmshah** [comment]
I'm not really sure what you're trying to achieve. When the `setInput` method is called, the assumption is that you're restarting the scanning process from the beginning. Hence, it makes sense to set the state of the lexer to `0`. That being said, you could simply write a [monkey](https://en.wikipedia.org/wiki/Monkey_patch) [patch](https://stackoverflow.com/q/5626193/783743) for your desired behavior. For example:

```javascript
class CustomLexer extends Lexer {
    constructor(defunct) {
        super(defunct);

        const setInput = {this};           // save the old setInput

        this.setInput = function (input) {
            const state = {this};          // save the current state
            setInput.call(this, input);    // call the old setInput
            this.state = state;            // restore the current state
            return this;
        };
    }
}
```

Now you can simply replace `new Lexer` with `new CustomLexer`. Hope that helps.

**Pull request closed without merging**
